#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _BTC_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

if ! bitcoin-cli help 2>/dev/null 1>&2; then
  echo "bitcoind was not running"
  exit 1
fi  

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec btc-help
  ;;
* )
  command_path="$(command -v "btc-$command" || true)"
  if [ ! -x "$command_path" ]; then
    exec "bitcoin-cli" "$@"
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
