#!/usr/bin/env bash

set -e

if [ "$1" = "--sh" ]; then
  sh=1
  shift
elif [ "$1" = "--no-sh" ]; then
  nosh=1
  shift
elif [ "$1" = "--not-cli" ]; then
  nocli=1
  shift
fi

shopt -s nullglob

{ # Deal with commands found on PATH
  for path in ${PATH//:/$'\n'}; do
    for command in "${path}/btc-"*; do
      command="${command##*btc-}"
      if [ -n "$sh" ]; then
        if [ ${command:0:3} = "sh-" ]; then
          echo ${command##sh-}
        fi
      elif [ -n "$nosh" ]; then
        if [ ${command:0:3} != "sh-" ]; then
          echo ${command##sh-}
        fi
      else
        echo ${command##sh-}
      fi
    done
  done

  # Deal with commands discovered from bitcoin-cli
  # Cache subcommands and summaries for 24 hours

  if [ ! -f ~/.btc-commands ] || find ~/.btc-commands -mtime +1 | grep -q '.'; then
    > ~/.btc-commands
    btc_commands=$(bitcoin-cli help | awk '{print $1}' | grep -v '==' | grep -v '^$' | sort -u)
    for btc_command in $btc_commands; do
      summary=$(bitcoin-cli help "$btc_command" | tail -n +2 | awk '/./ {print;exit}')
      echo "$btc_command|$summary" >> ~/.btc-commands
    done
  fi

  if [ -z "$nocli" ]; then
    cat ~/.btc-commands | cut -f1 -d'|'
  fi

} | sort -u
